import 'dart:ui';
import 'package:flutter/material.dart';

class MyColors {
  static const Color red = Color(0xFFFF0000);
  static const Color green = Color(0xFF00FF00);
  static const Color blue = Color(0xFF0000FF);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color maroon = Color(0xFF800000);
  static const Color olive = Color(0xFF808000);
  static const Color navy = Color(0xFF000080);
  static const Color purple = Color(0xFF800080);
  static const Color teal = Color(0xFF008080);
  static const Color tealAccent = Color(0xFF64FFDA);
  static const Color lightSeaGreen = Color(0xFF20B2AA);
  static const Color darkCyan = Color(0xFF008B8B);
  static const Color mediumTurquoise = Color(0xFF48D1CC);
  static const Color darkTurquoise = Color(0xFF00CED1);
  static const Color aqua = Color(0xFF00FFFF);
  static const Color cyan = Color(0xFF00FFFF);
  static const Color paleTurquoise = Color(0xFFAFEEEE);
  static const Color aquamarine = Color(0xFF7FFFD4);
  static const Color turquoise = Color(0xFF40E0D0);
  static const Color mediumAquamarine = Color(0xFF66CDAA);
  static const Color lightCyan = Color(0xFFE0FFFF);
  static const Color silver = Color(0xFFC0C0C0);
  static const Color gray = Color(0xFF808080);
  static const Color yellow = Color(0xFFFFFF00);
  static const Color fuchsia = Color(0xFFFF00FF);
  static const Color orange = Color(0xFFFFA500);
  static const Color pink = Color(0xFFFFC0CB);
  static const Color lime = Color(0xFF00FF00);
  static const Color magenta = Color(0xFFFF00FF);
  static const Color gold = Color(0xFFFFD700);
  static const Color brown = Color(0xFFA52A2A);
  static const Color coral = Color(0xFFFF7F50);
  static const Color salmon = Color(0xFFFA8072);
  static const Color khaki = Color(0xFFF0E68C);
  static const Color lavender = Color(0xFFE6E6FA);
  static const Color thistle = Color(0xFFD8BFD8);
  static const Color plum = Color(0xFFDDA0DD);
  static const Color violet = Color(0xFFEE82EE);
  static const Color indigo = Color(0xFF4B0082);
  static const Color crimson = Color(0xFFDC143C);
  static const Color fireBrick = Color(0xFFB22222);
  static const Color tomato = Color(0xFFFF6347);
  static const Color chocolate = Color(0xFFD2691E);
  static const Color sandyBrown = Color(0xFFF4A460);
  static const Color goldenRod = Color(0xFFDAA520);
  static const Color peru = Color(0xFFCD853F);
  static const Color darkOrange = Color(0xFFFF8C00);
  static const Color darkSalmon = Color(0xFFE9967A);
  static const Color lightSalmon = Color(0xFFFFA07A);
  static const Color darkGoldenRod = Color(0xFFB8860B);
  static const Color rosyBrown = Color(0xFFBC8F8F);
  static const Color paleVioletRed = Color(0xFFDB7093);
  static const Color lightCoral = Color(0xFFF08080);
  static const Color indianRed = Color(0xFFCD5C5C);
  static const Color mediumVioletRed = Color(0xFFC71585);
  static const Color orchid = Color(0xFFDA70D6);
  static const Color mediumOrchid = Color(0xFFBA55D3);
  static const Color darkOrchid = Color(0xFF9932CC);
  static const Color darkViolet = Color(0xFF9400D3);
  static const Color blueViolet = Color(0xFF8A2BE2);
  static const Color mediumPurple = Color(0xFF9370DB);
  static const Color slateBlue = Color(0xFF6A5ACD);
  static const Color mediumSlateBlue = Color(0xFF7B68EE);
  static const Color royalBlue = Color(0xFF4169E1);
  static const Color mediumBlue = Color(0xFF0000CD);
  static const Color darkBlue = Color(0xFF00008B);
  static const Color midnightBlue = Color(0xFF191970);
  static const Color darkSlateBlue = Color(0xFF483D8B);
  static const Color cornflowerBlue = Color(0xFF6495ED);
  static const Color lightSteelBlue = Color(0xFFB0C4DE);
  static const Color slateGray = Color(0xFF708090);
  static const Color lightSlateGray = Color(0xFF778899);
  static const Color skyBlue = Color(0xFF87CEEB);
  static const Color lightSkyBlue = Color(0xFF87CEFA);
  static const Color deepSkyBlue = Color(0xFF00BFFF);
  static const Color dodgerBlue = Color(0xFF1E90FF);
  static const Color steelBlue = Color(0xFF4682B4);
  static const Color aliceBlue = Color(0xFFF0F8FF);
  static const Color ghostWhite = Color(0xFFF8F8FF);
  static const Color mintCream = Color(0xFFF5FFFA);
  static const Color lavenderBlush = Color(0xFFFFF0F5);
  static const Color seashell = Color(0xFFFFF5EE);
  static const Color snow = Color(0xFFFFFAFA);
  static const Color white1 = Color(0xFFF1F5F9);
  static const Color honeyDew = Color(0xFFF0FFF0);
  static const Color ivory = Color(0xFFFFFFF0);
  static const Color linen = Color(0xFFFAF0E6);
  static const Color antiqueWhite = Color(0xFFFAEBD7);
  static const Color beige = Color(0xFFF5F5DC);
  static const Color wheat = Color(0xFFF5DEB3);
  static const Color floralWhite = Color(0xFFFFFAF0);
  static const Color oldLace = Color(0xFFFDF5E6);
  static const Color mistyRose = Color(0xFFFFE4E1);
  static const Color lightBlack1 = Color(0xFF2F2F2F); // Very dark gray
  static const Color lightBlack2 = Color(0xFF3A3A3A); // Dark gray
  static const Color lightBlack3 = Color(0xFF454545); // Dark gray
  static const Color lightBlack4 = Color(0xFF505050); // Medium-dark gray
  static const Color lightBlack5 = Color(0xFF5A5A5A); // Medium-dark gray
  static const Color lightBlack6 = Color(0xFF646464); // Medium gray
  static const Color oceanBlueStart = Color(0xFF2E3192);
  static const Color oceanBlueEnd = Color(0xFF1BFFFF);
  static const Color aquaMarineStart = Color(0xFF1A2980);
  static const Color aquaMarineEnd = Color(0xFF26D0CE);
  static const Color darkGray = Color(0xFF434343);
  static const Color darkPurple = Color(0xFF4B0082);
  static const Color deepBlue = Color(0xFF00008B);
  static const Color transparent = Colors.transparent;
  static const Color lightGray = Color(0xFFB0B0B0);
  static const Color darkBlueGrey1 = Color(0xFF263238); // Dark blue-grey
  static const Color darkBlueGrey2 = Color(0xFF37474F); // Slightly lighter dark blue-grey
  static const Color darkBlueGreyCustom = Color(0xFF1E3A4C); // Custom dark blue-grey
  static const Color customblack = Color(0xFF21222D);



}
